#!/bin/bash
# Copyright (C) 2011-2013 OpenStack Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

# dib-lint: disable=setu setpipefail
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -e

useradd -m jenkins
echo -e "0\n0" |passwd jenkins
adduser jenkins sudo
echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCxdKE8NQBMLA25tirMNOJeplEPox6JNt3YmF/FLnjBij/3tnhePjGMMqFxh1q70eV4Rv4CncjgZjUpFarWUvbxfovILUs3FjfW/o0XWLzvTdhToV1fkTKii2Eh1pFYLjzQ7waP3PSrXcslRGZojjKalUMWjl0DcDbVp5i4nlLVmPP+n8iZ9/SbYbZlWpqGigpsgOr4PStKEhT+jeqf1vgNT22WCtxWief+0C/Yguqg0GlXevwKZEOzUPO4ZyEmvNcUG5LRurz2mTAZFG/W52DaN5pFD2CYPvRzK/payVZeIW6Z9Ynf71KaIzTkqhvafBDjLhf2W/qTFNQSHISBm9bB zte@ubuntu224' >> /home/jenkins/.ssh/authorized_keys
#chown -R jenkins:jenkins /home/jenkins

